# my global config
global:
  scrape_interval: 10s 
  evaluation_interval: 10s 

scrape_configs:
  - job_name: "prometheus"

    static_configs:
      - targets: ["orderapi:15000"]
      - targets: ["storeapi:15000"]