{
 "title": "EasyEats",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Prometheus up status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count(up{job=\"prometheus\"})"
    }
   ]
  },
  {
   "title": "HTTP request by method",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (method) (flask_http_request_total)"
    }
   ]
  },
  {
   "title": "HTTP requests by status code",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (status) (flask_http_request_total)"
    }
   ]
  }
 ]
}